---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myweb
  name: crccheck/hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - image: localhost:5000
        imagePullPolicy: Always
        name: crccheck/hello-world

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myweb
  name: crccheck/hello-world
spec:
  ports:
  - nodePort: 8000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myweb
  type: NodePort
